### ISSUE TITLE
Is PivotTableJsonWriter support Subtotal ？

### ISSUE THREAD

**Issue by a764578566** [nreco/pivotdata#2]
PivotTableHtmlWriter support Subtotal . 
  
            var outputWr = new StringWriter();
            var pvtHtmlWr = new PivotTableHtmlWriter(outputWr);
            pvtHtmlWr.SubtotalRows = true;
            pvtHtmlWr.SubtotalDimensions = new string[] { "Date" };
            pvtHtmlWr.SubtotalColumns = true;

**Comment by VitaliyMF** [comment]
Currently sub-totals are supported in PivotTableHtmlWriter and PivotTableExcelWriter. 
JSON export often used to get pivoted data for charts, which don't need sub-totals. However, it is possible to add an option to PivotTableJsonWriter that will add sub-totals into the output ("ColumnKeys"/"RowKeys" may contain entries like ["Key1", null] for sub-total key).

**Comment by VitaliyMF** [comment]
Starting from NReco.PivotData.Extensions 1.5.4 `PivotTableJsonWriter` also can include sub-totals; this is controlled with SubtotalRows and SubtotalColumns properties (like in PivotTableHtmlWriter).
