### ISSUE TITLE
How to write code in group sorting?

### ISSUE THREAD

**Issue by a764578566** [nreco/pivotdata#3]
pvtTbl.SortRowKeysByColumnKey(new ValueKey( "Android APP"), 0, ListSortDirection.Ascending);

![image](https://user-images.githubusercontent.com/14343051/83130850-879dc080-a111-11ea-8bd9-ec3a19deb2a5.png)

But I hope is
![image](https://user-images.githubusercontent.com/14343051/83129278-2674ed80-a10f-11ea-995a-4616a801f33c.png)

**Comment by VitaliyMF** [comment]
If you want to sort rows by some criteria only inside group:

```
pvtTbl.PreserveGroupOrder = true;
```
