### ISSUE TITLE
How to write code show values?

### ISSUE THREAD

**Issue by a764578566** [nreco/pivotdata#4]
I hope is 
![image](https://user-images.githubusercontent.com/14343051/84260391-8b3b3980-ab4c-11ea-993f-4f5ca32b433b.png)
I write code is 
  
            pvtHtmlWr.TotalsColumn = false;
            pvtHtmlWr.TotalsRow = false;
            pvtHtmlWr.GrandTotal = false;
  
but is
![image](https://user-images.githubusercontent.com/14343051/84260475-b0c84300-ab4c-11ea-8c21-fd549462a53d.png)
if I write code is
  
            pvtHtmlWr.TotalsColumn = true;
            pvtHtmlWr.TotalsRow = true;
            pvtHtmlWr.GrandTotal = ture;
  
![image](https://user-images.githubusercontent.com/14343051/84260675-04d32780-ab4d-11ea-8f3f-66e03124c26d.png)

User does not check Totals

**Comment by VitaliyMF** [comment]
Sorry, I'm afraid I don't understand the question.

It looks like your pivot table has only dimensions for "Rows" (and no dimensions for "Columns") and as result, only "Totals" column(s) are possible. When you disable "TotalsColumn" you get just a columns that represent row dimensions, this is correct behavior.

BTW, you can customize "Totals" column(s) captions if needed: 

- use `PivotTableHtmlWriter.TotalsColumnHeaderText` property to change "Totals" to something else
- specify `PivotTableHtmlWriter.FormatMeasureHeader` handler to customize measure names ("Sum of [field]|, "Max of [field]") -- see this doc for more details: https://www.nrecosite.com/pivotdata/format-pivot-table.aspx
