### ISSUE TITLE
Easy Paginate PivotTable or PivotData

### ISSUE THREAD

**Issue by Guille9201** [nreco/pivotdata#5]
I'm using the PivotTableHtmlWriter but when I have too much data, the rending takes forever.

I found SliceQuery but it's only to filter data.

Thank you very much

**Comment by VitaliyMF** [comment]
Pivot table pagination just displays part of the table, it anyway requires fully loaded PivotTable data model. 

How many rows/columns do you have? Normally all in-memory functions work fine with pivot tables that have up to 1,000,000 cells (number of rows * number of columns). It is not much sense to work with huge pivot tables as they are for summary data by definition; to limit number of rows and/or columns you may filter your data on the data source level -- say, if this is SQL database it is efficient to filter data in the SQL GROUP BY query with WHERE conditions.

**Comment by Guille9201** [comment]
Sorry found the PaginatePivotTable.

**Comment by VitaliyMF** [comment]
> Sorry found the PaginatePivotTable

Take a look into "NReco.PivotData.Examples.ToolkitPivotBuilderMvc" (you can download it [here](https://www.nrecosite.com/pivot_data_library_net.aspx)), it illustrates how to use PaginatePivotTable.
