### ISSUE TITLE
.NET 6

### ISSUE THREAD

**Issue by pantonis** [nreco/pivotdata#6]
Is this library maintained? Was it updated to .NET 6?

**Comment by VitaliyMF** [comment]
Library is fully supported, however I don't have any issue reports in the core lib (NReco.PivotData nuget) -- so no need to update it.

A special build for NET5/NET6 is not needed as 'netstandard2.0' target is compatible with all modern .NET versions (I can confirm that - I personally use PivotData components in my own NET6 apps).

**Comment by pantonis** [comment]
What about major performance improvements in .NET 5 and 6. Don't you think that the library is good to take advantage of those?

**Comment by VitaliyMF** [comment]
When you use NReco.PivotData in your app that targets net6.0 all runtime optimizations are used (most of them are on JIT level), no need to recompile the library to get these benefits.

**Comment by pantonis** [comment]
btw where can I see some full examples?

**Comment by VitaliyMF** [comment]
Examples that use only NReco.PivotData nuget are in this repo: https://github.com/nreco/pivotdata/tree/master/examples

More advanced examples need NReco.PivotData.Extensions nuget (which is not free/open source), you may download them here: https://www.nrecosite.com/pivotdata_service.aspx  -- note that these examples are still target legacy .NET Framework, but all code can be used in .NET Core / NET6 apps. I have plans to migrate these examples to net6.0 soon.

**Comment by pantonis** [comment]
What is the difference between the two libraries? NReco.PivotData and NReco.PivotData.Extensions?
You need a better website :)

**Comment by VitaliyMF** [comment]
> What is the difference between the two libraries? NReco.PivotData and NReco.PivotData.Extensions?

NReco.PivotData implements basic infrastructure for aggregations and in-memory roll-ups. This is open source / free (under some limitations) part of the toolkit. 

All advanced things are in NReco.PivotData.Extensions (it depends on NReco.PivotData, and this is closed source / commercial product) - pivot tables HTML rendering & exports, table-level calculations (percentages, differences etc), loading pre-aggregated data from databases and supporting components that are needed for [web-based reports builder](http://pivottable.nrecosite.com/).

This division on 2 assemblies exists for historic/backward compatibility reasons. Even nowadays NReco.PivotData can be used separately, this depends on the usage.
